import { corsairQuery } from "@/corsair/server";

// Test natural language query generation with Cerebras
async function testQuery() {
  // This query will be auto-generated by Cerebras!
  const popularArtists = await corsairQuery("get artists with popularity greater than 80", {});
  return popularArtists;
}

// Trigger file watcher - testing improved Cerebras!
